#!/bin/bash
set -eu

HOOKS_DIR=$(dirname "${BASH_SOURCE[0]}")
BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
VCS_URL=$(git config --get remote.origin.url)
VCS_REF=$(git rev-parse --short HEAD)
VERSION=$(cat "${HOOKS_DIR}/../VERSION")
export DOCKER_CLI_EXPERIMENTAL=enabled

docker buildx build \
  --platform=linux/amd64,linux/arm64,linux/arm/v7 \
  --build-arg UNIFI_VERSION=$VERSION \
  --build-arg VCS_URL=$VCS_URL \
  --build-arg VCS_REF=$VCS_REF \
  --build-arg BUILD_DATE=$BUILD_DATE \
  -t $IMAGE_NAME \
  --load \
  .
