#!/bin/bash
set -eu

HOOKS_DIR=$(dirname "${BASH_SOURCE[0]}")
VERSION=$(cat "${HOOKS_DIR}/../VERSION")
VERSION_MINOR=${VERSION%.*}

for ALT_TAG in {$VERSION,$VERSION_MINOR}; do
  docker tag \
    "${IMAGE_NAME}" \
    "${DOCKER_REPO}:${ALT_TAG}"
  docker push \
    "${DOCKER_REPO}:${ALT_TAG}"
done