#!/bin/bash
set -eu

export DOCKER_CLI_EXPERIMENTAL=enabled

apt-get update -qq
apt-get install -y --no-install-recommends \
  qemu-user-static

docker run --rm --privileged \
  multiarch/qemu-user-static --reset -p yes

docker buildx create --use --name autobuild
docker buildx inspect --bootstrap

exit 0
